user www-data;
# worker_processes == same as "grep processor /proc/cpuinfo | wc -l"
worker_processes %%NGINX_WORKER_PROCESSES%%;
worker_rlimit_nofile 30000;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
#	worker_connections == not more than "ulimit -n"
	worker_connections 16384;
#	multi_accept on;
#	use epoll;
}

http {

	##
	# Basic Settings
	##

	# Hardening
	client_body_buffer_size  1k;
	client_header_buffer_size 1k;
	large_client_header_buffers 4 8k;  # requests with larger headers will be answered with 400 bad request, default is 4 8k;
	client_max_body_size %%NGINX_CLIENT_BODY_MAX_SIZE%%;  # required for large file uploads, default is 1M

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	types_hash_max_size 2048;  # default is 1024

	server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Timeout settings. See https://www.slingacademy.com/article/how-to-configure-timeouts-in-nginx/
	##
	# client_body_timeout 12;	# default 60
	# client_header_timeout 12;	# default 60
	# send_timeout 10;			# default 30
	# keepalive_timeout 15;		# default 65
	# keepalive_requests 100;
	# keepalive_disable msie6;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/access.log error;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_min_length 1000;
	gzip_http_version 1.1;
	gzip_proxied any;
	gzip_comp_level 5;  # Better balance of CPU vs Compression
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
	gzip_static on;	    # look for compressed .gz file before compressing (requires http_gzip_static_module)
	# gzip_vary on;
	# gzip_buffers 16 8k;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#	server {
#		listen	 localhost:110;
#		protocol	pop3;
#		proxy	  on;
#	}
#
#	server {
#		listen	 localhost:143;
#		protocol	imap;
#		proxy	  on;
#	}
#}
