[client]
log_level = info
url = https://landscape.canonical.com/message-system
ping_url = http://landscape.canonical.com/ping
data_path = /var/lib/landscape/client
computer_title = %%UBUNTU_LANDSCAPE_COMPUTER_TITLE%%
account_name = %%UBUNTU_LANDSCAPE_ACCOUNT_NAME%%
registration_key = %%UBUNTU_LANDSCAPE_REGISTRATION_KEY%%

# Active Monitoring (Safe)
monitor_only = true
include_manager_plugins = Reporter, MaxCpuReport, RebootReport, ShutdownReport, ResourceMonitor, LogManagement, ComputerInfo

# Explicitly exclude active components (Disables Cloud Root Execution)
exclude_manager_plugins = ScriptExecution, PackageManagement
manage_sources_list_d = false
script_users = none